---
apiVersion: v1
kind: Secret
metadata:
  name: vcloud-basic-auth
  namespace: kube-system
data:
  username: ""
  password: ""
  # Refresh token can be omitted when using username and password
  refreshToken: ""
