# If you're trying to install this CSI Driver to a k8s cluster installed manually, via kubespray, etc., 
# please set clusterid to NO_RDE_<some-uuid>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-csi-configmap
  namespace: kube-system
data:
  vcloud-csi-config.yaml: |
    vcd:
      host: VCD_HOST
      org: ORG
      vdc: OVDC
      vAppName: VAPP 
    clusterid: CLUSTER_ID
immutable: true
