---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcloud-capvcd-zones
  namespace: kube-system
data:
  vcloud-cse-zones.yaml: |+
    zoneType: dcgroup
    zones:
    - name: ZONE_NAME
      ovdcName: OVDC
---
