---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "vcd-disk-xfs"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: vcd-disk-xfs
provisioner: named-disk.csi.cloud-director.vmware.com
parameters:
  csi.storage.k8s.io/fstype: "xfs"
  storageProfile: "*"
  filesystem: "xfs"
---