---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ext4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: "vcd-disk-ext4"
---
