---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-filesystem
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: "vcd-disk-dev"
---
